### ISSUE TITLE
Not able to hear the mobile part

### ISSUE THREAD

**Issue by inoutglobal** [pregalla/jitsi#1]
Dear,

I´ve run your script on Ubuntu 20 to install Jitsi,Jibri and Jigasi. Great work, thanks for sharing it.

I´m able to place a call from Conference meet me to my mobile call.
But I am not able to hear the mobile part. 

Last weekend I was able to reinstall only Jitsi with jigasi and it works good. I can hear sounds in both ways. It works good as well.

Unfornately  If I setup jibri together then the issue happens again.

I guess the issue is related with some conflict between jibri and jigasi process.  Can you think what could it be? Any clues?

Regards,

Edson

**Comment by pregalla** [comment]
Hi. Jibri and Jigasi should not have any conflict. Cannot think of any reason why that would happen?

Jitsi community forum may provide some help.

**Comment by pregalla** [comment]
I see you have opened a thread there already...hope you get clarity there...

**Comment by inoutglobal** [comment]
Yes, it is driving me crazy. I have already installed it in Debian, Ubuntu, in differents version, NAT, without NAT. But i have found that Jigasi only works ok if Jibri is not installed together. It could be a silly thing that i am not able to check.

**Comment by pregalla** [comment]
Closing this as this is not an issue with the setup...
